export default [
    {
        id: 1,
        src:require('~/Assets/Images/car1.jpg'),
        name:'BMW 8-serie 2-door coupe grey',
        year:'2021',
        automatic:'Automatic',
        petrol:'Petrol',
        FrontWD:'Front Wheel Drive',
        price:'$62,000',
        lists:[
            {
                id: '1',
                src:require('~/Assets/Images/car2.jpg'),
                name:'Chevrolet Camaro 2-door convertible blue',
                price:'$40,000',
                year:'2021',
                automatic:'Automatic',
                diesel:'Diesel',
            },
            {
                id: '2',
                src:require('~/Assets/Images/car3.jpg'),
                name:'Ferrari LaFerrari 2-door coupe red',
                price:'$810,000',
                year:'2021',
                automatic:'Automatic',
                diesel:'Diesel',
            },
            {
                id: '3',
                src:require('~/Assets/Images/car4.jpg'),
                name:'Audi A8 4-door sedan silver',
                price:'$70,000',
                year:'2021',
                automatic:'Automatic',
                diesel:'Diesel',
            },
            {
                id: '4',
                src:require('~/Assets/Images/car5.jpg'),
                name:'Mercedes-Benz S-class 2-door coupe silver',
                price:'$76,000',
                year:'2021',
                automatic:'Automatic',
                diesel:'Diesel',
            }
        ]
    },
    {
        id: 2,
        src:require('~/Assets/Images/car6.jpg'),
        name:'  Mercedes-Benz AMG GT 2-door coupe yellow',
        year:'2020',
        automatic:'Automatic',
        petrol:'Petrol',
        FrontWD:'160,000 miles',
        price:'$14,600',
        lists:[
            {
                id: '1',
                src:require('~/Assets/Images/car7.jpg'),
                name:'Porsche Macan 5-door SUV blue',
                price:'$14,600',
                year:'2018',
                automatic:'190,000 miles ',
                diesel:'Diesel',
            },
            {
                id: '2',
                src:require('~/Assets/Images/car8.jpg'),
                name:'Audi A4 4-door sedan blue',
                price:'$23,000',
                year:'2020',
                automatic:'245,000 miles',
                diesel:'Manual',
            },
            {
                id: '3',
                src:require('~/Assets/Images/car9.jpg'),
                name:' Audi A8 4-door sedan blue',
                price:'$14,600',
                year:'2017',
                automatic:'400,000 miles',
                diesel:'Diesel',
            },
            {
                id: '4',
                src:require('~/Assets/Images/car10.jpg'),
                name:'Audi A8 4-door sedan silver',
                price:'$30,000',
                year:'2016',
                automatic:'400,000 miles',
                diesel:'Manual',
            }
        ]
    },
]