export default [
    {
        id: 1,
        view:'19',
        lists:[
            {
                id: '1',
                src: require('~/Assets/Images/audi/car1.jpg'),
                name: 'Audi A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '2',
                src: require('~/Assets/Images/audi/car2.jpg'),
                name: 'Audi A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '3',
                src: require('~/Assets/Images/audi/car3.jpg'),
                name: 'Audi A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '4',
                src: require('~/Assets/Images/audi/car4.jpg'),
                name: 'Audi A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '5',
                src: require('~/Assets/Images/audi/car5.jpg'),
                name: 'Audi A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '6',
                src: require('~/Assets/Images/audi/car6.jpg'),
                name: 'Audi A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '7',
                src: require('~/Assets/Images/audi/car7.jpg'),
                name: 'Audi A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '8',
                src: require('~/Assets/Images/audi/car8.jpg'),
                name: 'Audi A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '9',
                src: require('~/Assets/Images/audi/car9.jpg'),
                name: 'Audi A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '10',
                src: require('~/Assets/Images/audi/car10.jpg'),
                name: 'Audi A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '11',
                src: require('~/Assets/Images/audi/car11.jpg'),
                name: 'Audi A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '12',
                src: require('~/Assets/Images/audi/car12.jpg'),
                name: 'BMW 8-serie 2-door coupe grey',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
        ],
    },
    {
        id: 2,
        lists:[
            {
                id: '1',
                src: require('~/Assets/Images/audi/car1.jpg'),
                name: 'BMW A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '2',
                src: require('~/Assets/Images/audi/car2.jpg'),
                name: 'BMW A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '3',
                src: require('~/Assets/Images/audi/car3.jpg'),
                name: 'BMW A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '4',
                src: require('~/Assets/Images/audi/car4.jpg'),
                name: 'BMW A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '5',
                src: require('~/Assets/Images/BMW/car5.jpg'),
                name: 'BMW A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '6',
                src: require('~/Assets/Images/BMW/car6.jpg'),
                name: 'BMW A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '7',
                src: require('~/Assets/Images/BMW/car7.jpg'),
                name: 'BMW A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '8',
                src: require('~/Assets/Images/BMW/car8.jpg'),
                name: 'BMW A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '9',
                src: require('~/Assets/Images/BMW/car9.jpg'),
                name: 'BMW A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '10',
                src: require('~/Assets/Images/BMW/car10.jpg'),
                name: 'BMW A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '11',
                src: require('~/Assets/Images/BMW/car11.jpg'),
                name: 'BMW A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '12',
                src: require('~/Assets/Images/BMW/car12.jpg'),
                name: 'BMW A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
        ],
    },
    {
        id: 3,
        lists:[
            {
                id: '1',
                src: require('~/Assets/Images/audi/car5.jpg'),
                name: 'Cadillac A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '2',
                src: require('~/Assets/Images/audi/car6.jpg'),
                name: 'Cadillac A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '3',
                src: require('~/Assets/Images/audi/car7.jpg'),
                name: 'Cadillac A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '4',
                src: require('~/Assets/Images/audi/car8.jpg'),
                name: 'Cadillac A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '5',
                src: require('~/Assets/Images/Cadillac/car5.jpg'),
                name: 'Cadillac A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '6',
                src: require('~/Assets/Images/Cadillac/car6.jpg'),
                name: 'Cadillac A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '7',
                src: require('~/Assets/Images/Cadillac/car7.jpg'),
                name: 'Cadillac A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '8',
                src: require('~/Assets/Images/Cadillac/car8.jpg'),
                name: 'Cadillac A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '9',
                src: require('~/Assets/Images/Cadillac/car9.jpg'),
                name: 'Cadillac A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '10',
                src: require('~/Assets/Images/Cadillac/car10.jpg'),
                name: 'Cadillac A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '11',
                src: require('~/Assets/Images/Cadillac/car11.jpg'),
                name: 'Cadillac A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '12',
                src: require('~/Assets/Images/Cadillac/car12.jpg'),
                name: 'Cadillac A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
        ],
    },
    {
        id: 4,
        lists:[
            {
                id: '1',
                src: require('~/Assets/Images/audi/car9.jpg'),
                name: 'Ferrari A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '2',
                src: require('~/Assets/Images/audi/car10.jpg'),
                name: 'Ferrari A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '3',
                src: require('~/Assets/Images/audi/car11.jpg'),
                name: 'Ferrari A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '4',
                src: require('~/Assets/Images/audi/car12.jpg'),
                name: 'Ferrari A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '5',
                src: require('~/Assets/Images/Ferrari/car5.jpg'),
                name: 'Ferrari A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '6',
                src: require('~/Assets/Images/Ferrari/car6.jpg'),
                name: 'Ferrari A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '7',
                src: require('~/Assets/Images/Ferrari/car7.jpg'),
                name: 'Ferrari A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '8',
                src: require('~/Assets/Images/Ferrari/car8.jpg'),
                name: 'Ferrari A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
            {
                id: '9',
                src: require('~/Assets/Images/Ferrari/car9.jpg'),
                name: 'Ferrari A4 4-door sedan blue',
                price: '$23,000',
                year: '2020',
                automatic: 'Automatic',
                mile:'245,000 miles',
                manual:'Manual',
                diesel: 'Diesel',
            },
            {
                id: '10',
                src: require('~/Assets/Images/Ferrari/car10.jpg'),
                name: 'Ferrari A8 4-door sedan silver ',
                price: '$70,000',
                year: '2021',
                automatic: 'Automatic',
                diesel: 'Diesel',
            },
            {
                id: '11',
                src: require('~/Assets/Images/Ferrari/car11.jpg'),
                name: 'Ferrari A8 4-door sedan blue',
                price: '$14,600',
                year: '2017',
                automatic: 'Automatic',
                mile:'400,000 miles',
                diesel: 'Diesel',
            },
            {
                id: '12',
                src: require('~/Assets/Images/Ferrari/car12.jpg'),
                name: 'Ferrari A8 4-door sedan silver',
                price: '$30,000',
                year: '2016',
                automatic: 'Automatic',
                diesel: 'Diesel',
                mile:'400,000 miles',
                manual:'Manual',
            },
        ],
    },
];
